# generated by datamodel-codegen:
#   filename:  entry_exit_logs.json
#   timestamp: 2024-09-29T10:33:45+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Model(BaseModel):
    id: int
    guild_id: Optional[int] = None
    user_id: int
    voicechannel_id: Optional[int] = None
    timestamp_entry: Optional[str] = None
    timestamp_exit: Optional[str] = None
    study_target_id: Optional[int] = None
    created_at: str
    updated_at: str
