# generated by datamodel-codegen:
#   filename:  studytimelogs.json
#   timestamp: 2024-09-29T10:33:45+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, constr


class Model(BaseModel):
    id: int
    study_dt: Optional[str] = None
    guild_id: Optional[constr(max_length=20)] = None
    member_id: Optional[constr(max_length=20)] = None
    voice_id: Optional[constr(max_length=20)] = None
    access: Optional[constr(max_length=10)] = None
    studytime_min: Optional[int] = None
    studytag_no: Optional[constr(max_length=10)] = None
    excluded_record: Optional[int] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    studytimelogs_chk_1: Optional[str] = None
