# generated by datamodel-codegen:
#   filename:  studymembers.json
#   timestamp: 2024-09-29T10:33:46+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, constr


class Model(BaseModel):
    id: int
    guild_id: Optional[constr(max_length=20)] = None
    member_id: Optional[constr(max_length=20)] = None
    member_name: Optional[constr(max_length=50)] = None
    joined_dt: Optional[str] = None
    enrollment: Optional[int] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    studymembers_chk_1: Optional[str] = None
