# generated by datamodel-codegen:
#   filename:  studytimelogs.json
#   timestamp: 2024-09-29T08:39:12+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Column(BaseModel):
    name: str
    type: str
    null: Optional[bool] = None
    charset: Optional[str] = None
    collate: Optional[str] = None


class Part(BaseModel):
    column: str


class PrimaryKey(BaseModel):
    parts: List[Part]


class Model(BaseModel):
    name: str
    columns: List[Column]
    primary_key: PrimaryKey
    charset: str
    collate: str
