# generated by datamodel-codegen:
#   filename:  studytimes_logs.json
#   timestamp: 2024-09-29T10:33:44+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Model(BaseModel):
    id: int
    guild_id: Optional[int] = None
    user_id: int
    voicechannel_id: Optional[int] = None
    studydate: str
    studytime_min: int
    study_target_id: Optional[int] = None
    created_at: str
    updated_at: str
